# Generated by Django 6.0.2 on 2026-02-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlkeWallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='banco',
            field=models.CharField(choices=[('banco_estado', 'BancoEstado'), ('banco_chile', 'Banco de Chile'), ('santander', 'Santander'), ('bci', 'BCI'), ('scotiabank', 'Scotiabank'), ('itau', 'Itaú'), ('falabella', 'Banco Falabella'), ('ripley', 'Banco Ripley'), ('security', 'Banco Security'), ('consorcio', 'Banco Consorcio'), ('bice', 'BICE'), ('hsbc', 'HSBC'), ('internacional', 'Banco Internacional'), ('coopeuch', 'Coopeuch')], default='banco_estado', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='numero_cuenta',
            field=models.CharField(default='0000000000', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='tipo_cuenta',
            field=models.CharField(choices=[('vista', 'Cuenta Vista'), ('corriente', 'Cuenta Corriente'), ('ahorro', 'Cuenta de Ahorro')], default='vista', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('owner', 'numero_cuenta')},
        ),
    ]
